# Generated by Django 2.0.6 on 2018-06-14 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown...', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('gps_lattitude', models.FloatField(blank=True, null=True)),
                ('gps_longitude', models.FloatField(blank=True, null=True)),
                ('addr_line', models.CharField(max_length=300)),
                ('zipcode', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown...', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('first_name', models.CharField(default='FirstName', max_length=200)),
                ('last_name', models.CharField(default='LastName', max_length=200)),
                ('nick_name', models.CharField(blank=True, default='NickName', max_length=200, null=True)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('x', 'Other')], max_length=1, null=True)),
                ('email_id', models.EmailField(max_length=200)),
                ('contact_no', models.DecimalField(decimal_places=0, max_digits=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ui.Address')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown...', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ui.Address')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown...', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created date')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated date')),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('ui', 'Urgent & Important'), ('u', 'Urgent'), ('i', 'Important'), ('tp', 'Not Urgent and Not Important')], max_length=2)),
                ('when', models.DateTimeField()),
                ('duration', models.PositiveIntegerField()),
                ('remind', models.BooleanField(default=True)),
                ('along_with', models.ManyToManyField(to='ui.Person')),
                ('where', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.Place')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='FirstName', max_length=200)),
                ('last_name', models.CharField(default='LastName', max_length=200)),
                ('nick_name', models.CharField(blank=True, default='NickName', max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.UserProfile'),
        ),
    ]
